name = "ZMQ"
uuid = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
version = "1.2.1"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
ZeroMQ_jll = "8f1865be-045e-5c20-9c9f-bfbfb0764568"

[compat]
ZeroMQ_jll = "4"
julia = "1.3"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test", "Statistics"]
