name = "ZMQ"
uuid = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
version = "1.2.5"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
ZeroMQ_jll = "8f1865be-045e-5c20-9c9f-bfbfb0764568"

[compat]
Aqua = "0.8.7"
FileWatching = "<0.0.1, 1"
PrecompileTools = "1"
Sockets = "<0.0.1, 1"
Test = "<0.0.1, 1"
ZeroMQ_jll = "4"
julia = "1.3"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
